name: Docker Image CI

on:
  push:
    branches: [ "2023.3.x" ]
  pull_request:
    branches: [ "2023.3.x" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dockerhub login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
    - name: Build webapp dockerfile (with push)
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        docker buildx build \
        --platform=linux/amd64,linux/arm/v7,linux/arm64 \
        --output "type=image,push=true" \
        --file ./client/web/own.Dockerfile ./client/web \
        --tag cyzhou314/corteza-webapp:latest
    - name: Build server dockerfile (with push)
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        docker buildx build \
        --platform=linux/amd64,linux/arm/v7,linux/arm64 \
        --output "type=image,push=true" \
        --file ./server/Dockerfile.snapshot ./server \
        --tag cyzhou314/corteza-server:latest
